language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -q -r requirements.txt --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source pypuppetdb -m py.test --pep8
  - ./bandit.sh
after_success:
  - coveralls
notifications:
  email: false
