name: build docs

on: [push, pull_request]

jobs:
  build-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install --upgrade -r docs/requirements.txt
          python setup.py develop
      - name: Build docs
        run: |
          cd docs
          make html
