name: Linters

on: [push, pull_request]

jobs:
  black-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Black Code Formatter
        uses: psf/black@stable
